version: '3.8'

services:
  postgres:
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_DB: appointments
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdatadb:/var/lib/postgresql/data

volumes:
  pgdatadb:
    name: pgdata-appointments-volume
networks:
  database:
    driver: bridge
